from .authentication_views import *
from .patient_dash_views import *
from .staff_dash_views import *
from .patient_forms_views import *
from .staff_forms_views import *
from .patient_crud_views import *
from .staff_crud_views import *
from .data_analysis import *
from .resetpassword import *
