# Generated by Django 5.0.4 on 2024-04-19 11:55

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('birth_date', models.DateField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChildDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_of_birth', models.CharField(max_length=50)),
                ('birth_weight', models.FloatField()),
                ('birth_order', models.CharField(max_length=5)),
                ('mother_name', models.CharField(max_length=50)),
                ('birth_length', models.FloatField()),
                ('birth_time', models.CharField(max_length=50)),
                ('del_type_nsd', models.BooleanField(default=False)),
                ('del_type_cs', models.BooleanField(default=False)),
                ('del_type_dos', models.BooleanField(default=False)),
                ('exclusively_bf', models.BooleanField(default=False)),
                ('exclusively_mixed', models.BooleanField(default=False)),
                ('exclusively_milk', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EconomicNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('philhealth_num', models.CharField(blank=True, max_length=15)),
                ('nhts_num', models.CharField(blank=True, max_length=50)),
                ('patient_4ps_member', models.BooleanField(default=False)),
                ('brgy_num', models.CharField(blank=True, max_length=50)),
                ('family_num', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=10)),
                ('record_type', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImmunizationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetanus_toxoid_mother_status', models.CharField(blank=True, default='', max_length=50)),
                ('bcg', models.BooleanField(default=False)),
                ('hepa', models.BooleanField(default=False)),
                ('pental_1', models.BooleanField(default=False)),
                ('pental_2', models.BooleanField(default=False)),
                ('pental_3', models.BooleanField(default=False)),
                ('opv_1', models.BooleanField(default=False)),
                ('opv_2', models.BooleanField(default=False)),
                ('opv_3', models.BooleanField(default=False)),
                ('rota_1', models.BooleanField(default=False)),
                ('rota_2', models.BooleanField(default=False)),
                ('rota_3', models.BooleanField(default=False)),
                ('amv', models.BooleanField(default=False)),
                ('mr', models.BooleanField(default=False)),
                ('mmr', models.BooleanField(default=False)),
                ('other_immunization', models.CharField(blank=True, default='', max_length=50)),
                ('vitamin_a', models.BooleanField(default=False)),
                ('breastfeeding', models.BooleanField(default=False)),
                ('deworming', models.BooleanField(default=False)),
                ('deworm_date', models.DateField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabetes', models.BooleanField(default=False)),
                ('asthma', models.BooleanField(default=False)),
                ('hpn', models.BooleanField(default=False)),
                ('ptb', models.BooleanField(default=False)),
                ('cancer', models.BooleanField(default=False)),
                ('cough', models.BooleanField(default=False)),
                ('other_medical_history', models.CharField(blank=True, max_length=255)),
                ('medication_taken', models.CharField(blank=True, max_length=255)),
                ('family_planning', models.BooleanField(default=False)),
                ('adult_immunization', models.CharField(blank=True, max_length=100)),
                ('immunization_date', models.DateField(blank=True, default='', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewbornStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ns_place', models.CharField(blank=True, default='', max_length=50)),
                ('ns_date', models.DateField(blank=True, default=None, null=True)),
                ('bcg_date', models.DateField(blank=True, default=None, null=True)),
                ('bcg_place', models.CharField(blank=True, default='', max_length=50)),
                ('dpt_opv_date', models.DateField(blank=True, default=None, null=True)),
                ('dpt_opv_place', models.CharField(blank=True, default='', max_length=60)),
                ('pcv_date', models.DateField(blank=True, default=None, null=True)),
                ('pcv_place', models.CharField(blank=True, default='', max_length=50)),
                ('ipv_date', models.DateField(blank=True, default=None, null=True)),
                ('ipv_place', models.CharField(blank=True, default='', max_length=50)),
                ('hepa_date', models.DateField(blank=True, default=None, null=True)),
                ('hepa_place', models.CharField(blank=True, default='', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PediatricDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_age', models.CharField(max_length=50)),
                ('father_age', models.CharField(max_length=50)),
                ('birth_order', models.CharField(max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoker', models.BooleanField(default=False)),
                ('alcohol_intake', models.BooleanField(default=False)),
                ('prohibited_drug', models.BooleanField(default=False)),
                ('cigarette_sticks', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('civil_status', models.CharField(blank=True, default='', max_length=50)),
                ('religion', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('educational_attainment', models.CharField(blank=True, default='', max_length=100)),
                ('occupation', models.CharField(blank=True, default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pediatric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('economic_numbers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.economicnumbers')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.form')),
                ('immunization_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pediatric_immunization_history', to='base.immunizationhistory')),
                ('medical_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.medicalhistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pediatric_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pediatricdetails')),
                ('social_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.socialhistory')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('child_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.childdetails')),
                ('economic_numbers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.economicnumbers')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.form')),
                ('newborn_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.newbornstatus')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('economic_numbers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.economicnumbers')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.form')),
                ('medical_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.medicalhistory')),
                ('social_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.socialhistory')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.userprofile')),
            ],
        ),
    ]
