# Generated by Django 5.0.4 on 2024-04-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childdetails',
            name='birth_length_in_inches',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
