# Generated by Django 5.0.4 on 2024-04-27 14:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_doctororders_filled_by_nursenotes_filled_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField(blank=True)),
                ('findings', models.TextField(blank=True)),
                ('impression', models.TextField(blank=True)),
                ('management', models.TextField(blank=True)),
                ('filled_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('filled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filled_doctor_order', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='adult',
            name='doctor_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.doctororder'),
        ),
        migrations.AlterField(
            model_name='child',
            name='doctor_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.doctororder'),
        ),
        migrations.AlterField(
            model_name='pediatric',
            name='doctor_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.doctororder'),
        ),
        migrations.DeleteModel(
            name='DoctorOrders',
        ),
    ]
